microservice-chart: &microservice-chart
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-wisp-converter-technical-support
    tag: "0.3.2-7-feat-migrate-report-generator"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress: &ingress
    create: true
    host: "weuprod.nodo.internal.platform.pagopa.it"
    path: /pagopa-wisp-converter-technical-support(/|$)(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources: &resources
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "768Mi"
      cpu: "0.50"
  autoscaling: &autoscaling
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig: &envConfig
    WEBSITE_SITE_NAME: 'pagopawispconverterts' # required to show cloud role name in application insights
    ENV: 'aks-prod'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'WARN'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    SERVICE_NAME: "pagopa-wisp-converter-technical-support"
    COSMOS_URI: "https://pagopa-p-weu-nodo-wispconv-cosmos-account.documents.azure.com:443/"
    COSMOS_READ_REGION: "North Europe"
    DATAEXPLORER_URL: "https://pagopapdataexplorer.westeurope.kusto.windows.net"
  secretProvider:
    create: true
    envSecrets: &envSecret
      # required
      APPLICATIONINSIGHTS_CONNECTION_STRING: 'azure-insight-connection-string'
      COSMOS_KEY: 'cosmosdb-wisp-converter-account-key'
    keyvault:
      name: "pagopa-p-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-wisp-converter-technical-support
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
# 1 - Standard service application
app:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
  resources:
    !!merge <<: *resources
  envConfig:
    !!merge <<: *envConfig
  envSecret:
    !!merge <<: *envSecret
# 2 - Only-cronjob application
cron:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /pagopa-wisp-converter-technical-support-jobs(/|$)(.*)
  resources:
    !!merge <<: *resources
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "1024Mi"
      cpu: "0.50"
  autoscaling:
    !!merge <<: *autoscaling
    enable: false
    minReplica: 1
    maxReplica: 1
  envConfig:
    !!merge <<: *envConfig
    CRONJOB_REPORTGENERATION_ENABLED: 'true'
    CRONJOB_REPORTGENERATION_DAILY_SCHEDULE: '00 00 00 * * *'
    CRONJOB_REPORTGENERATION_WEEKLY_SCHEDULE: '00 00 07 * * 1'
    CRONJOB_REPORTGENERATION_MONTHLY_SCHEDULE: '00 30 07 1 * *'
  envSecret:
    !!merge <<: *envSecret
